[build]
  command = "cd netlify/functions && npm install && cd ../../ && pip install -r requirements.txt"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express"]
  included_files = ["**/*.py", "chatbot.py", "requirements.txt"]
